from project.animal import Animal
from project.dog import Dog
from project.cat import Cat


animal = Animal()
print(animal.eat())   # eating...

dog = Dog()
print(dog.eat())      # eating...
print(dog.bark())     # barking...

cat = Cat()
print(cat.eat())      # eating...
print(cat.meow())     # meowing...
